language: node_js
node_js:
  - "stable"

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - nyc --reporter=lcov mocha --recursive test/unit
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bash <(curl -s https://codecov.io/bash) -C -F unittests
  - nyc --reporter=lcov mocha --recursive test/system
  - bash <(curl -s https://codecov.io/bash) -C -F systemtests
